# https://sls.zone/pages/run/hosting-for-a-serverless-project-on-s3/
service: frontend

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-s3-sync
  - serverless-stack-termination-protection

custom:
  serverlessTerminationProtection:
    stages:
      - prod
  # domainNames:
  #   prod: www.test.com
  #   stag: www.test.net
  #   dev: www.test.dev
  # domainName: ${self:custom.domainNames.${self:provider.stage}}
  domainName: www.test.dev
  bucketName: ${self:custom.domainName}
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: build
      params:
        - index.html:
            CacheControl: "no-cache, max-age=30"
        - outdated-browser.html:
            CacheControl: "no-cache, max-age=30"
        - "**/*.js":
            CacheControl: "public, max-age=31536000"
        - "**/*.css":
            CacheControl: "public, max-age=31536000"
        - "static/media/*":
            CacheControl: "public, max-age=31536000"

# The "Resources" your "Functions" use.  Raw AWS CloudFormation goes in here.
resources:
  Resources:
    WebAppCloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: ${self:service}-${self:provider.stage}

    WebAppBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    WebAppBucketPolicy:
      Type: AWS::S3::BucketPolicy
      DependsOn:
        - WebAppCloudFrontOriginAccessIdentity
      Properties:
        Bucket:
          Ref: WebAppBucket
        PolicyDocument:
          # https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-policy-language-overview.html
          Statement:
            - Sid: CanonicalUserReadGetObject
              Effect: Allow
              Principal:
                CanonicalUser:
                  # https://docs.aws.amazon.com/ko_kr/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html
                  # https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudfront/get-cloud-front-origin-access-identity.html
                  Fn::GetAtt:
                    [WebAppCloudFrontOriginAccessIdentity, S3CanonicalUserId]
              Action:
                - s3:GetObject
              # https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-arn-format.html
              # https://yonghyuc.wordpress.com/2021/01/20/fnjoin/
              Resource:
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Ref: WebAppBucket
                    - "/*"

    WebAppCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      DependsOn: WebAppBucketPolicy
      Properties:
        DistributionConfig:
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            TargetOriginId: ${self:service}
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-viewercertificate.html#cfn-cloudfront-distribution-viewercertificate-acmcertificatearn
          # ViewerCertificate:
          #   AcmCertificateArn: ${ssm:/${self:provider.stage}/${self:service}/acm_certificate_arn~true}
          #   SslSupportMethod: sni-only
          DefaultRootObject: index.html
          # Aliases:
          #   - ${self:custom.domainName}
          Enabled: true
          HttpVersion: http2
          Logging:
            IncludeCookies: false
            Bucket: ${self:custom.bucketName}.s3.amazonaws.com
            Prefix: cf-logs
          Origins:
            - DomainName: ${self:custom.bucketName}.s3.amazonaws.com
              Id: ${self:service}
              S3OriginConfig:
                # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-s3originconfig.html#cfn-cloudfront-distribution-s3originconfig-originaccessidentity
                OriginAccessIdentity:
                  Fn::Join:
                    - ""
                    - - "origin-access-identity/cloudfront/"
                      - Ref: WebAppCloudFrontOriginAccessIdentity

  # The "Outputs" that your AWS CloudFormation Stack should produce.  This allows references between services.
  Outputs:
    WebAppBucket:
      Value:
        Ref: WebAppBucket
    WebAppCloudFrontDistributionDomainName:
      Value:
        Fn::GetAtt: [WebAppCloudFrontDistribution, DomainName]
